### PR TITLE
Add View To The Blog App

### PR DESCRIPTION
**Pull request by zieeco**
**In this milestone, I did the following**

- Added styling to all views files and layouts to match the wireframes
- Ensured there were no linter error

This part of my blop app features adding basic styles to match the wireframe design

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @zieeco, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ All linters passing
✔️ Professional readme
✔️ Correct git-flow

## Required 
- [ ] Kindly make sure to display your app correctly, following the wireframe provided.
- [ ] When I tried adding users, posts and comments. It doesn't add anything to the database. Kindly fix it and make sure that the added data should be displayed on the page.

Screenshot 2022-07-14 at 2 51 26 PM


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zieeco** [comment]
@sja-thedude, I don't seem to understand what you mean as my app is working perfectly okay.

**Comment by sja-thedude** [comment]
> @sja-thedude, I don't seem to understand what you mean as my app is working perfectly okay.

On my side, your app doesn’t work as it should.

**Comment by zieeco** [comment]
@sja-thedude, the app works perfectly, You can not add a user without specifying the post_counter which the validating is checking and making sure its not nil.
so specify the post counter by adding 0, and it will work

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @zieeco,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
